specVersion: 1.0.0
indexerHints:
  prune: auto
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: Holons.sol
    network: sepolia
    source:
      address: "0xAbbbA8be2154c6BC2743C798B046677EF12e8f86"
      abi: Holons.sol
      startBlock: 7831350
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - NewFlavor
        - NewHolon
      abis:
        - name: Holons.sol
          file: ./abis/Holons.sol.json
      eventHandlers:
        - event: NewFlavor(indexed address,string)
          handler: handleNewFlavor
        - event: NewHolon(string,address)
          handler: handleNewHolon
      file: ./src/holons-sol.ts

templates:
  - name: Splitter
    kind: ethereum/contract
    network: sepolia
    source:
      abi: Splitter
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/holon-template.ts
      entities:
        - HolonContract
        - RewardDistribution
        - MemberReward       
      abis:
        - name: Splitter
          file: ./abis/Splitter.json
      eventHandlers:
        - event: RewardDistributed(indexed address,uint256,uint256,string)
          handler: handleRewardDistributed
        - event: MemberRewarded(indexed address,indexed address,uint256,bool,string)
          handler: handleMemberRewarded

  - name: Zoned
    kind: ethereum/contract
    network: sepolia
    source:
      abi: Zoned
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/holon-template.ts
      entities:
        - HolonContract
        - RewardDistribution
        - MemberReward       
      abis:
        - name: Zoned
          file: ./abis/Zoned.json
      eventHandlers:
        - event: RewardDistributed(indexed address,uint256,uint256,string)
          handler: handleRewardDistributed
        - event: MemberRewarded(indexed address,indexed address,uint256,bool,string)
          handler: handleMemberRewarded

  - name: Managed
    kind: ethereum/contract
    network: sepolia
    source:
      abi: Managed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/holon-template.ts
      entities:
        - HolonContract
        - RewardDistribution
        - MemberReward       
      abis:
        - name: Managed
          file: ./abis/Managed.json
      eventHandlers:
        - event: RewardDistributed(indexed address,uint256,uint256,string)
          handler: handleRewardDistributed
        - event: MemberRewarded(indexed address,indexed address,uint256,bool,string)
          handler: handleMemberRewarded