specVersion: 1.0.0
indexerHints:
  prune: auto
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: Holons.sol
    network: mainnet
    source:
      address: "0xe4eb561155afce723bb1ff8606fbfe9b28d5d38d"
      abi: Holons.sol
      startBlock: 0
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - NewFlavor
        - NewHolon
      abis:
        - name: Holons.sol
          file: ./abis/Holons.json
      eventHandlers:
        # - event: NewFlavor(indexed address,string)
        #   handler: handleNewFlavor
        - event: NewHolon(string,address)
          handler: handleNewHolon
      file: ./src/holons.ts

  # ManagedFactory
  - kind: ethereum/contract
    name: ManagedFactory
    network: mainnet
    source:
      address: "0x057ef64e23666f000b34ae31332854acbd1c8544"
      abi: ManagedFactory
      startBlock: 0
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Managed
        - ManagedFactory
      abis:
        - name: ManagedFactory
          file: ./abis/ManagedFactory.json
      eventHandlers:
        - event: ManagedContractCreated(indexed address,indexed string,string)
          handler: handleManagedContractCreated
      file: ./src/managedFactory.ts

  # ZonedFactory
  - kind: ethereum/contract
    name: ZonedFactory
    network: mainnet
    source:
      address: "0x261d8c5e9742e6f7f1076fa1f560894524e19cad"
      abi: ZonedFactory
      startBlock: 0
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Zoned
        - ZonedFactory
      abis:
        - name: ZonedFactory
          file: ./abis/ZonedFactory.json
      eventHandlers:
        - event: ZonedContractCreated(indexed address,indexed string,string,uint256)
          handler: handleZonedContractCreated
      file: ./src/zonedFactory.ts

templates:
  - name: Splitter
    kind: ethereum/contract
    network: mainnet
    source:
      abi: Splitter
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/splitter.ts
      entities:
        - HolonContract
        - RewardDistribution
        - MemberReward       
      abis:
        - name: Splitter
          file: ./abis/Splitter.json
      eventHandlers:
        - event: ChildHolonCreated(indexed address,indexed string,string)
          handler: handleChildHolonCreated
        - event: RewardDistributed(indexed address,uint256,uint256,string)
          handler: handleRewardDistributed
        - event: MemberRewarded(indexed address,indexed address,uint256,bool,string)
          handler: handleMemberRewarded

  - name: Zoned
    kind: ethereum/contract
    network: mainnet
    source:
      abi: Zoned
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/splitter.ts
      entities:
        - HolonContract
        - RewardDistribution
        - MemberReward       
      abis:
        - name: Zoned
          file: ./abis/Zoned.json
      eventHandlers:
        - event: RewardDistributed(indexed address,uint256,uint256,string)
          handler: handleRewardDistributed
        - event: MemberRewarded(indexed address,indexed address,uint256,bool,string)
          handler: handleMemberRewarded

  - name: Managed
    kind: ethereum/contract
    network: mainnet
    source:
      abi: Managed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/splitter.ts
      entities:
        - HolonContract
        - RewardDistribution
        - MemberReward       
      abis:
        - name: Managed
          file: ./abis/Managed.json
      eventHandlers:
        - event: RewardDistributed(indexed address,uint256,uint256,string)
          handler: handleRewardDistributed
        - event: MemberRewarded(indexed address,indexed address,uint256,bool,string)
          handler: handleMemberRewarded